name: CI

on:
  push:
    branches:
      - main

jobs:
  check_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies with retry
        run: |
          pushd daemon/web
          n=0
          until [ $n -ge 5 ]
          do
            npm ci && break
            n=$((n+1))
            echo "Retrying npm ci ($n)..."
            sleep 15
          done
          npm run build
          popd

      - name: Cargo check
        run: NO_FIRMWARE_BIN=true cargo check --verbose

  build_rayhunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies with retry
        run: |
          pushd daemon/web
          n=0
          until [ $n -ge 5 ]
          do
            npm ci && break
            n=$((n+1))
            echo "Retrying npm ci ($n)..."
            sleep 15
          done
          npm run build
          popd

      - name: Build rayhunter-daemon (armv7)
        run: |
          cargo build -p rayhunter-daemon --bin rayhunter-daemon --target armv7-unknown-linux-musleabihf --profile=firmware
